post_install()
{
   systemctl daemon-reload
}

pre_upgrade()
{
   # first stop the old one, as we're gonna change service names
   systemctl stop ropieee1-web
}

post_upgrade()
{
#   cd /opt/RoPieee/web
#   npm cache verify
#   rm -rf /opt/RoPieee/web/node_modules
#   npm install

   systemctl daemon-reload
   systemctl restart ropieee-web

   # ok, let's get rid of the 'old' directory
   rm -rf /opt/RoPieee/web
}
