post_install()
{
   cd /opt/RoPieee/web
   npm install

   systemctl daemon-reload
   systemctl enable ropieee-web
   systemctl start ropieee-web
}

post_upgrade()
{
   cd /opt/RoPieee/web
   npm install

   systemctl daemon-reload
   systemctl restart ropieee-web

   # introduce audio setting
   if [ $( grep -c rp_audio /etc/ropieee.conf ) -eq 0 ]
   then
      echo "rp_audio=usb" >> /etc/ropieee.conf
   fi
}
